// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUNNcIBZ6sHp7QjM7OZ2QYF2brjj3TT6o',
    appId: '1:692204602881:web:ac70b6471180ee04dea200',
    messagingSenderId: '692204602881',
    projectId: 'datadomtt',
    authDomain: 'datadomtt.firebaseapp.com',
    storageBucket: 'datadomtt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjLoIAnUMk9tSS1gqeJWSvdudbWnNeGGc',
    appId: '1:692204602881:android:c7e6e1477ad5f95adea200',
    messagingSenderId: '692204602881',
    projectId: 'datadomtt',
    storageBucket: 'datadomtt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMdeQcJvm0-PJSNUwsPnOio9FlwISZZoo',
    appId: '1:692204602881:ios:86ed18723ffe2bc7dea200',
    messagingSenderId: '692204602881',
    projectId: 'datadomtt',
    storageBucket: 'datadomtt.firebasestorage.app',
    iosBundleId: 'com.example.datadom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMdeQcJvm0-PJSNUwsPnOio9FlwISZZoo',
    appId: '1:692204602881:ios:86ed18723ffe2bc7dea200',
    messagingSenderId: '692204602881',
    projectId: 'datadomtt',
    storageBucket: 'datadomtt.firebasestorage.app',
    iosBundleId: 'com.example.datadom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUNNcIBZ6sHp7QjM7OZ2QYF2brjj3TT6o',
    appId: '1:692204602881:web:4ea6bd83c8f32c24dea200',
    messagingSenderId: '692204602881',
    projectId: 'datadomtt',
    authDomain: 'datadomtt.firebaseapp.com',
    storageBucket: 'datadomtt.firebasestorage.app',
  );
}
